language: python
env:
  global:
    - PIP_DEPS="flake8 pytest coveralls pytest-cov"
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install --upgrade pip
  - pip --version
  - travis_retry pip install -e .[dev]
script:
  - flake8 `find . -name \*.py | grep -v setup.py | grep -v
    version.py | grep -v __init__.py | grep -v /doc/`
  - mkdir for_test
  - cd for_test
  - travis_wait 30 py.test --pyargs afqinsight --cov-report term-missing --cov-config .coveragerc --cov=afqinsight
  - cd ..
after_success:
  - coveralls
